using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;

namespace TrustTunnel.Desktop;

public sealed class LocalizationManager : INotifyPropertyChanged
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["Common.Save"] = "Save",
        ["Common.Cancel"] = "Cancel",
        ["Common.Close"] = "Close",
        ["Common.Apply"] = "Apply",
        ["Common.Reset"] = "Reset",
        ["Common.Delete"] = "Delete",
        ["Common.Duplicate"] = "Duplicate",
        ["Common.CreateProfile"] = "Create profile",
        ["Common.DeleteProfile"] = "Delete selected profile",
        ["Common.ShowPassword"] = "Show password",
        ["Common.ShowSocksPassword"] = "Show SOCKS5 password",
        ["Common.ShowClientRandom"] = "Show client random",
        ["Common.None"] = "None",

        ["Language.English"] = "English",
        ["Language.Russian"] = "Русский",
        ["Language.Chinese"] = "中文",
        ["Language.Persian"] = "فارسی",

        ["Settings.Title"] = "Settings",
        ["Settings.Appearance"] = "Appearance",
        ["Settings.Proxy"] = "Proxy",
        ["Settings.Diagnostics"] = "Diagnostics",
        ["Settings.About"] = "About",
        ["Settings.Theme"] = "THEME",
        ["Settings.ColorScheme"] = "Color scheme",
        ["Settings.ColorSchemeHint"] = "Light or dark interface theme",
        ["Settings.Light"] = "Light",
        ["Settings.Dark"] = "Dark",
        ["Settings.AccentColor"] = "Accent color",
        ["Settings.AccentColorHint"] = "Used for buttons, the ring, and selection",
        ["Settings.Density"] = "Density",
        ["Settings.DensityHint"] = "Spacing and control sizes",
        ["Settings.Comfortable"] = "Comfortable",
        ["Settings.Compact"] = "Compact",
        ["Settings.Language"] = "Language",
        ["Settings.LanguageHint"] = "Interface language. First launch follows the system language.",
        ["Settings.Window"] = "WINDOW",
        ["Settings.StartMode"] = "Startup mode",
        ["Settings.StartModeHint"] = "Expanded connection panel or compact window",
        ["Settings.Expanded"] = "Expanded",
        ["Settings.Windows"] = "WINDOWS",
        ["Settings.SystemProxy"] = "System proxy",
        ["Settings.SystemProxyHint"] = "Automatically set Windows proxy to local SOCKS5 when a SOCKS5 profile is connected. TUN does not need this.",
        ["Settings.SocksListener"] = "SOCKS5 LISTENER",
        ["Settings.LanAccess"] = "LAN access",
        ["Settings.LanAccessHint"] = "Allow SOCKS5 connections from other devices in the local network",
        ["Settings.SocksAddress"] = "SOCKS5 address",
        ["Settings.SocksAddressHint"] = "Single local address and port for all SOCKS5 profiles",
        ["Settings.ConnectionTests"] = "CONNECTION TESTS",
        ["Settings.PingHost"] = "Ping host",
        ["Settings.PingHostHint"] = "Address for latency checks",
        ["Settings.HttpsUrl"] = "HTTPS test URL",
        ["Settings.HttpsUrlHint"] = "Address for internet access checks",
        ["Settings.DiagnosticsTimeout"] = "Diagnostics timeout",
        ["Settings.DiagnosticsTimeoutHint"] = "Maximum response wait time",
        ["Settings.Version"] = "Version 0.1 · Alpha",
        ["Settings.Description"] = "Proxy Open Hub Windows client · TrustTunnel native core",
        ["Settings.Updates"] = "Updates",
        ["Settings.UpdatesHint"] = "Current build is up to date",
        ["Settings.Check"] = "Check",

        ["Profile.WindowTitle"] = "Profile settings",
        ["Profile.Title"] = "Settings: {0}",
        ["Profile.Subtitle"] = "Connection, routing, security, and local proxy options.",
        ["Profile.Badge"] = "Profile",
        ["Profile.Connection"] = "Connection",
        ["Profile.Switches"] = "Switches",
        ["Profile.RoutingDns"] = "Routing / DNS",
        ["Profile.Local"] = "Local listener",
        ["Profile.Advanced"] = "Advanced",
        ["Profile.Name"] = "Name",
        ["Profile.HostnameSni"] = "Hostname / SNI",
        ["Profile.CustomSni"] = "Custom SNI",
        ["Profile.Addresses"] = "Addresses, one per line",
        ["Profile.Username"] = "Username",
        ["Profile.Password"] = "Password",
        ["Profile.Transport"] = "Transport",
        ["Profile.ClientMode"] = "Client mode",
        ["Profile.FallbackProtocol"] = "Fallback protocol",
        ["Profile.TunMode"] = "TUN system VPN",
        ["Profile.SocksMode"] = "SOCKS5 proxy",
        ["Profile.PostQuantum"] = "Post-quantum group",
        ["Profile.AntiDpi"] = "Anti-DPI",
        ["Profile.SkipVerification"] = "Skip certificate verification",
        ["Profile.KillSwitch"] = "Kill switch",
        ["Profile.ChangeSystemDns"] = "Change system DNS",
        ["Profile.UseExistingTun"] = "Use existing TUN",
        ["Profile.ServiceMode"] = "Windows Service mode",
        ["Profile.AutoConnect"] = "Auto-connect",
        ["Profile.RoutingProfile"] = "Routing profile",
        ["Profile.RoutingMode"] = "Routing mode",
        ["Profile.RoutingGeneral"] = "VPN for everything except rules",
        ["Profile.RoutingSelective"] = "VPN only for rules",
        ["Profile.DnsUpstreams"] = "DNS upstreams",
        ["Profile.Exclusions"] = "Rules: domains, wildcard, CIDR",
        ["Profile.IncludedRoutes"] = "Included TUN routes",
        ["Profile.ExcludedRoutes"] = "Excluded TUN routes",
        ["Profile.KillSwitchPorts"] = "Kill switch allow ports",
        ["Profile.Mtu"] = "MTU",
        ["Profile.TcpRecv"] = "TCP receive buffer",
        ["Profile.TcpSend"] = "TCP send buffer",
        ["Profile.LocalHint"] = "Only profile-specific values stay here. SOCKS5 address and LAN access are configured in application settings.",
        ["Profile.TunBoundIf"] = "TUN bound_if",
        ["Profile.TunDeviceName"] = "TUN device name",
        ["Profile.SocksUsername"] = "SOCKS5 username",
        ["Profile.SocksPassword"] = "SOCKS5 password",
        ["Profile.ClientRandom"] = "Client random",
        ["Profile.CertificatePem"] = "Certificate PEM",
        ["Profile.SaveTooltip"] = "Save profile settings",
        ["Profile.CancelTooltip"] = "Close without saving",
        ["Profile.Valid"] = "Profile is valid.",
        ["Profile.UnsafeTitle"] = "Unsafe setting",
        ["Profile.UnsafeMessage"] = "Certificate verification is disabled. This reduces connection security. Save anyway?",
        ["Profile.NotSavedTitle"] = "Profile was not saved",

        ["Routing.Title"] = "Routing profiles",
        ["Routing.Subtitle"] = "Routing profiles apply to servers from the main window.",
        ["Routing.Profiles"] = "Profiles",
        ["Routing.Name"] = "Name",
        ["Routing.Description"] = "Description",
        ["Routing.Mode"] = "Routing mode",
        ["Routing.General"] = "VPN for everything except rules",
        ["Routing.Selective"] = "VPN only for rules",
        ["Routing.Presets"] = "Quick presets",
        ["Routing.RuBypass"] = "RU outside VPN",
        ["Routing.RuBypassTip"] = "Add rules for .ru, .su and .рф",
        ["Routing.LocalBypass"] = "Local network outside VPN",
        ["Routing.LocalBypassShort"] = "Local network outside",
        ["Routing.LocalBypassTip"] = "Add private IPv4 networks outside VPN",
        ["Routing.SelectivePreset"] = "Only list through VPN",
        ["Routing.SelectivePresetTip"] = "Switch profile to selective mode",
        ["Routing.NewProfile"] = "Routing profile",
        ["Routing.Rules"] = "Rules: domains, wildcard, CIDR",
        ["Routing.RulesHint"] = "One rule per line: *.ru, *.xn--p1ai, example.com, 10.0.0.0/8",
        ["Routing.KillSwitchPorts"] = "Ports allowed by kill switch",
        ["Routing.SaveProfile"] = "Save profile",
        ["Routing.SaveProfileTip"] = "Save selected routing profile",

        ["Toml.Title"] = "Edit TOML",
        ["Toml.Subtitle"] = "Edit TOML. Secrets are hidden in preview, but saved and copied in full TOML.",
        ["Toml.ShowSensitive"] = "Show sensitive data",
        ["Toml.ShowSensitiveTip"] = "Show password, client_random and certificate in the editor",
        ["Toml.Copy"] = "Copy TOML",

        ["Import.Title"] = "Import profile",
        ["Import.Subtitle"] = "If the clipboard contains a tt:// link or TOML, the profile can be added immediately.",
        ["Import.CheckingClipboard"] = "Checking clipboard...",
        ["Import.ClipboardFound"] = "TrustTunnel link found in clipboard.",
        ["Import.ClipboardMissing"] = "No TrustTunnel link found in clipboard. Paste a link manually or import TOML.",
        ["Import.ClipboardNoText"] = "Clipboard does not contain text.",
        ["Import.Failed"] = "Import failed",
        ["Import.FromClipboard"] = "Import from clipboard",
        ["Import.PasteLink"] = "Paste link",
        ["Import.Toml"] = "TOML",
        ["Import.Manual"] = "Manual",
        ["ImportToml.Title"] = "Import TOML",
        ["ImportToml.Subtitle"] = "Paste a TOML config. Passwords will be moved to the secret store.",
        ["ImportToml.Import"] = "Import",

        ["Main.Servers"] = "SERVERS",
        ["Main.AddServer"] = "Add Server",
        ["Main.NoServer"] = "No server selected",
        ["Main.ImportConfig"] = "Import a config",
        ["Main.ImportOrAdd"] = "Import a config or add a profile.",
        ["Main.Connect"] = "Connect",
        ["Main.Disconnect"] = "Disconnect",
        ["Main.Connecting"] = "Connecting...",
        ["Main.Disconnecting"] = "Disconnecting...",
        ["Main.Reconnecting"] = "Reconnecting...",
        ["Main.Connected"] = "Connected",
        ["Main.Disconnected"] = "Disconnected",
        ["Main.ConnectionError"] = "Connection error",
        ["Main.Ready"] = "Ready to connect",
        ["Main.SelectServerAndConnect"] = "Select a server and connect",
        ["Main.Download"] = "DOWNLOAD",
        ["Main.Upload"] = "UPLOAD",
        ["Main.Protocol"] = "PROTOCOL",
        ["Main.Ping"] = "PING",
        ["Main.Session"] = "SESSION",
        ["Main.Route"] = "ROUTE",
        ["Main.OpenCores"] = "OPEN CORES · 1",
        ["Main.ActiveCore"] = "Active core",
        ["Main.Open"] = "Open",
        ["Main.Soon"] = "Soon",
        ["Main.TrustedRelease"] = "Trusted GitHub release",
        ["Main.ToggleTheme"] = "Toggle light/dark theme",
        ["Main.RoutingProfiles"] = "Routing profiles",
        ["Main.EditToml"] = "Edit TOML",
        ["Main.Logs"] = "Logs",
        ["Main.Settings"] = "Application settings",
        ["Main.ServerParameters"] = "Server parameters",
        ["Main.DeleteServerTitle"] = "Delete server",
        ["Main.DeleteServerMessage"] = "Delete \"{0}\" and related secrets?",
        ["Main.SessionActive"] = "Active",
        ["Main.SessionStart"] = "Start",
        ["Main.SessionRetry"] = "Retry",
        ["Main.SessionStop"] = "Stop",
        ["Main.SessionError"] = "Error",
        ["Main.SelectServerTitle"] = "Proxy Open Hub",
        ["Main.SelectServerMessage"] = "Select a server first.",

        ["Manual.Title"] = "Add server",
        ["Manual.Subtitle"] = "Fill only the basic fields. Everything else can be changed later in profile settings.",
        ["Manual.Address"] = "Host:port address",
        ["Manual.QuickOptions"] = "Quick options",
        ["Manual.SaveTooltip"] = "Save server",
        ["TextViewer.CopyHint"] = "Content can be copied to the clipboard.",
        ["TextViewer.ViewHint"] = "Text content preview.",
        ["TextViewer.Copy"] = "Copy",
    };

    private static readonly IReadOnlyDictionary<string, string> Russian = new Dictionary<string, string>
    {
        ["Common.Save"] = "Сохранить",
        ["Common.Cancel"] = "Отмена",
        ["Common.Close"] = "Закрыть",
        ["Common.Apply"] = "Применить",
        ["Common.Reset"] = "Сбросить",
        ["Common.Delete"] = "Удалить",
        ["Common.Duplicate"] = "Дублировать",
        ["Common.CreateProfile"] = "Создать профиль",
        ["Common.DeleteProfile"] = "Удалить выбранный профиль",
        ["Common.ShowPassword"] = "Показать пароль",
        ["Common.ShowSocksPassword"] = "Показать пароль SOCKS5",
        ["Common.ShowClientRandom"] = "Показать client random",
        ["Common.None"] = "Нет",

        ["Language.English"] = "English",
        ["Language.Russian"] = "Русский",
        ["Language.Chinese"] = "中文",
        ["Language.Persian"] = "فارسی",

        ["Settings.Title"] = "Настройки",
        ["Settings.Appearance"] = "Внешний вид",
        ["Settings.Proxy"] = "Прокси",
        ["Settings.Diagnostics"] = "Диагностика",
        ["Settings.About"] = "О программе",
        ["Settings.Theme"] = "ТЕМА",
        ["Settings.ColorScheme"] = "Цветовая схема",
        ["Settings.ColorSchemeHint"] = "Светлая или темная тема интерфейса",
        ["Settings.Light"] = "Светлая",
        ["Settings.Dark"] = "Темная",
        ["Settings.AccentColor"] = "Акцентный цвет",
        ["Settings.AccentColorHint"] = "Применяется к кнопкам, кольцу и выделению",
        ["Settings.Density"] = "Плотность",
        ["Settings.DensityHint"] = "Отступы и размеры элементов",
        ["Settings.Comfortable"] = "Просторно",
        ["Settings.Compact"] = "Компактно",
        ["Settings.Language"] = "Язык",
        ["Settings.LanguageHint"] = "Язык интерфейса. При первом запуске берётся системный язык.",
        ["Settings.Window"] = "ОКНО",
        ["Settings.StartMode"] = "Режим при запуске",
        ["Settings.StartModeHint"] = "Развернутое окно с панелью подключения или компактное",
        ["Settings.Expanded"] = "Развернутое",
        ["Settings.Windows"] = "WINDOWS",
        ["Settings.SystemProxy"] = "Системный proxy",
        ["Settings.SystemProxyHint"] = "Автоматически ставить Windows proxy на локальный SOCKS5 при подключении профиля SOCKS5. Для TUN не требуется.",
        ["Settings.SocksListener"] = "SOCKS5 LISTENER",
        ["Settings.LanAccess"] = "Доступ из LAN",
        ["Settings.LanAccessHint"] = "Разрешить подключения к SOCKS5 с других устройств локальной сети",
        ["Settings.SocksAddress"] = "Адрес SOCKS5",
        ["Settings.SocksAddressHint"] = "Единый локальный адрес и порт для всех SOCKS5-профилей",
        ["Settings.ConnectionTests"] = "ПРОВЕРКИ СОЕДИНЕНИЯ",
        ["Settings.PingHost"] = "Ping-хост",
        ["Settings.PingHostHint"] = "Адрес для проверки задержки",
        ["Settings.HttpsUrl"] = "URL HTTPS-теста",
        ["Settings.HttpsUrlHint"] = "Адрес для проверки доступа в интернет",
        ["Settings.DiagnosticsTimeout"] = "Таймаут диагностики",
        ["Settings.DiagnosticsTimeoutHint"] = "Максимальное ожидание ответа",
        ["Settings.Version"] = "Версия 0.1 · Alpha",
        ["Settings.Description"] = "Windows-клиент Proxy Open Hub · нативное ядро TrustTunnel",
        ["Settings.Updates"] = "Обновления",
        ["Settings.UpdatesHint"] = "Текущая сборка актуальна",
        ["Settings.Check"] = "Проверить",

        ["Profile.WindowTitle"] = "Параметры профиля",
        ["Profile.Title"] = "Параметры: {0}",
        ["Profile.Subtitle"] = "Подключение, маршруты, безопасность и локальные прокси.",
        ["Profile.Badge"] = "Профиль",
        ["Profile.Connection"] = "Подключение",
        ["Profile.Switches"] = "Переключатели",
        ["Profile.RoutingDns"] = "Маршруты / DNS",
        ["Profile.Local"] = "Локальный listener",
        ["Profile.Advanced"] = "Дополнительно",
        ["Profile.Name"] = "Название",
        ["Profile.HostnameSni"] = "Hostname / SNI",
        ["Profile.CustomSni"] = "Custom SNI",
        ["Profile.Addresses"] = "Адреса, по одному в строке",
        ["Profile.Username"] = "Логин",
        ["Profile.Password"] = "Пароль",
        ["Profile.Transport"] = "Транспорт",
        ["Profile.ClientMode"] = "Режим клиента",
        ["Profile.FallbackProtocol"] = "Fallback protocol",
        ["Profile.TunMode"] = "TUN system VPN",
        ["Profile.SocksMode"] = "SOCKS5 proxy",
        ["Profile.PostQuantum"] = "Post-quantum group",
        ["Profile.AntiDpi"] = "Anti-DPI",
        ["Profile.SkipVerification"] = "Отключить проверку сертификата",
        ["Profile.KillSwitch"] = "Kill switch",
        ["Profile.ChangeSystemDns"] = "Менять системный DNS",
        ["Profile.UseExistingTun"] = "Использовать существующий TUN",
        ["Profile.ServiceMode"] = "Режим службы Windows",
        ["Profile.AutoConnect"] = "Автоподключение",
        ["Profile.RoutingProfile"] = "Профиль маршрутизации",
        ["Profile.RoutingMode"] = "Режим маршрутизации",
        ["Profile.RoutingGeneral"] = "VPN для всего, кроме правил",
        ["Profile.RoutingSelective"] = "VPN только для правил",
        ["Profile.DnsUpstreams"] = "DNS upstreams",
        ["Profile.Exclusions"] = "Правила: домены, wildcard и CIDR",
        ["Profile.IncludedRoutes"] = "Включённые TUN-маршруты",
        ["Profile.ExcludedRoutes"] = "Исключённые TUN-маршруты",
        ["Profile.KillSwitchPorts"] = "Порты, разрешённые kill switch",
        ["Profile.Mtu"] = "MTU",
        ["Profile.TcpRecv"] = "TCP receive buffer",
        ["Profile.TcpSend"] = "TCP send buffer",
        ["Profile.LocalHint"] = "Здесь остаются только параметры, уникальные для профиля. Адрес SOCKS5 и доступ из LAN задаются в настройках приложения.",
        ["Profile.TunBoundIf"] = "TUN bound_if",
        ["Profile.TunDeviceName"] = "TUN device name",
        ["Profile.SocksUsername"] = "SOCKS5 username",
        ["Profile.SocksPassword"] = "SOCKS5 password",
        ["Profile.ClientRandom"] = "Client random",
        ["Profile.CertificatePem"] = "Certificate PEM",
        ["Profile.SaveTooltip"] = "Сохранить параметры профиля",
        ["Profile.CancelTooltip"] = "Закрыть без сохранения",
        ["Profile.Valid"] = "Профиль валиден.",
        ["Profile.UnsafeTitle"] = "Опасная настройка",
        ["Profile.UnsafeMessage"] = "Проверка сертификата отключена. Это снижает безопасность подключения. Сохранить?",
        ["Profile.NotSavedTitle"] = "Профиль не сохранён",

        ["Routing.Title"] = "Профили маршрутизации",
        ["Routing.Subtitle"] = "Профили маршрутизации применяются к серверам из главного окна.",
        ["Routing.Profiles"] = "Профили",
        ["Routing.Name"] = "Название",
        ["Routing.Description"] = "Описание",
        ["Routing.Mode"] = "Режим маршрутизации",
        ["Routing.General"] = "VPN для всего, кроме правил",
        ["Routing.Selective"] = "VPN только для правил",
        ["Routing.Presets"] = "Быстрые пресеты",
        ["Routing.RuBypass"] = "RU мимо VPN",
        ["Routing.RuBypassTip"] = "Добавить правила для .ru, .su и .рф",
        ["Routing.LocalBypass"] = "Локальная сеть мимо VPN",
        ["Routing.LocalBypassShort"] = "Локальная сеть мимо",
        ["Routing.LocalBypassTip"] = "Добавить частные IPv4-сети в обход VPN",
        ["Routing.SelectivePreset"] = "Только список через VPN",
        ["Routing.SelectivePresetTip"] = "Переключить профиль в режим selective",
        ["Routing.NewProfile"] = "Профиль маршрутизации",
        ["Routing.Rules"] = "Правила: домены, wildcard и CIDR",
        ["Routing.RulesHint"] = "По одному правилу в строке: *.ru, *.xn--p1ai, example.com, 10.0.0.0/8",
        ["Routing.KillSwitchPorts"] = "Порты, разрешённые kill switch",
        ["Routing.SaveProfile"] = "Сохранить профиль",
        ["Routing.SaveProfileTip"] = "Сохранить выбранный routing profile",

        ["Toml.Title"] = "Редактировать TOML",
        ["Toml.Subtitle"] = "Редактируйте TOML. Секреты скрыты в предпросмотре, но сохраняются и копируются в полном TOML.",
        ["Toml.ShowSensitive"] = "Показать чувствительные данные",
        ["Toml.ShowSensitiveTip"] = "Показать password, client_random и certificate в редакторе",
        ["Toml.Copy"] = "Скопировать TOML",

        ["Import.Title"] = "Импорт профиля",
        ["Import.Subtitle"] = "Если в буфере обмена есть tt:// ссылка или TOML, профиль можно добавить сразу.",
        ["Import.CheckingClipboard"] = "Проверяю буфер обмена...",
        ["Import.ClipboardFound"] = "В буфере обмена найдена TrustTunnel-ссылка.",
        ["Import.ClipboardMissing"] = "TrustTunnel-ссылка в буфере не найдена. Можно вставить ссылку вручную или импортировать TOML.",
        ["Import.ClipboardNoText"] = "В буфере обмена нет текста.",
        ["Import.Failed"] = "Импорт не выполнен",
        ["Import.FromClipboard"] = "Импорт из буфера",
        ["Import.PasteLink"] = "Вставить ссылку",
        ["Import.Toml"] = "TOML",
        ["Import.Manual"] = "Вручную",
        ["ImportToml.Title"] = "Импорт TOML",
        ["ImportToml.Subtitle"] = "Вставьте TOML-конфиг. Пароли будут перенесены в secret store.",
        ["ImportToml.Import"] = "Импортировать",

        ["Main.Servers"] = "СЕРВЕРЫ",
        ["Main.AddServer"] = "Добавить сервер",
        ["Main.NoServer"] = "Сервер не выбран",
        ["Main.ImportConfig"] = "Импортируйте конфиг",
        ["Main.ImportOrAdd"] = "Импортируйте конфиг или добавьте профиль.",
        ["Main.Connect"] = "Подключиться",
        ["Main.Disconnect"] = "Отключиться",
        ["Main.Connecting"] = "Подключение...",
        ["Main.Disconnecting"] = "Отключение...",
        ["Main.Reconnecting"] = "Переподключение...",
        ["Main.Connected"] = "Подключено",
        ["Main.Disconnected"] = "Отключено",
        ["Main.ConnectionError"] = "Ошибка подключения",
        ["Main.Ready"] = "Готово к подключению",
        ["Main.SelectServerAndConnect"] = "Выберите сервер и подключитесь",
        ["Main.Download"] = "ЗАГРУЗКА",
        ["Main.Upload"] = "ОТДАЧА",
        ["Main.Protocol"] = "ПРОТОКОЛ",
        ["Main.Ping"] = "PING",
        ["Main.Session"] = "СЕССИЯ",
        ["Main.Route"] = "МАРШРУТ",
        ["Main.OpenCores"] = "ОТКРЫТЫЕ ЯДРА · 1",
        ["Main.ActiveCore"] = "Активное ядро",
        ["Main.Open"] = "Открыто",
        ["Main.Soon"] = "Скоро",
        ["Main.TrustedRelease"] = "Доверенный GitHub release",
        ["Main.ToggleTheme"] = "Переключить светлую/тёмную тему",
        ["Main.RoutingProfiles"] = "Профили маршрутов",
        ["Main.EditToml"] = "Редактировать TOML",
        ["Main.Logs"] = "Логи",
        ["Main.Settings"] = "Настройки приложения",
        ["Main.ServerParameters"] = "Параметры сервера",
        ["Main.DeleteServerTitle"] = "Удаление сервера",
        ["Main.DeleteServerMessage"] = "Удалить \"{0}\" и связанные секреты?",
        ["Main.SessionActive"] = "Активно",
        ["Main.SessionStart"] = "Старт",
        ["Main.SessionRetry"] = "Повтор",
        ["Main.SessionStop"] = "Стоп",
        ["Main.SessionError"] = "Ошибка",
        ["Main.SelectServerTitle"] = "Proxy Open Hub",
        ["Main.SelectServerMessage"] = "Сначала выберите сервер.",

        ["Manual.Title"] = "Добавить сервер",
        ["Manual.Subtitle"] = "Заполните только базовые поля. Остальное можно настроить позже в параметрах профиля.",
        ["Manual.Address"] = "Адрес host:port",
        ["Manual.QuickOptions"] = "Быстрые опции",
        ["Manual.SaveTooltip"] = "Сохранить сервер",
        ["TextViewer.CopyHint"] = "Содержимое можно скопировать в буфер обмена.",
        ["TextViewer.ViewHint"] = "Просмотр текстового содержимого.",
        ["TextViewer.Copy"] = "Скопировать",
    };

    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
    {
        ["Common.Save"] = "保存",
        ["Common.Cancel"] = "取消",
        ["Common.Close"] = "关闭",
        ["Common.Apply"] = "应用",
        ["Common.Reset"] = "重置",
        ["Common.Delete"] = "删除",
        ["Common.Duplicate"] = "复制",
        ["Common.CreateProfile"] = "创建配置",
        ["Common.DeleteProfile"] = "删除所选配置",
        ["Common.ShowPassword"] = "显示密码",
        ["Common.ShowSocksPassword"] = "显示 SOCKS5 密码",
        ["Common.ShowClientRandom"] = "显示 client random",
        ["Common.None"] = "无",
        ["Language.English"] = "English",
        ["Language.Russian"] = "Русский",
        ["Language.Chinese"] = "中文",
        ["Language.Persian"] = "فارسی",
        ["Settings.Title"] = "设置",
        ["Settings.Appearance"] = "外观",
        ["Settings.Proxy"] = "代理",
        ["Settings.Diagnostics"] = "诊断",
        ["Settings.About"] = "关于",
        ["Settings.Theme"] = "主题",
        ["Settings.ColorScheme"] = "配色方案",
        ["Settings.ColorSchemeHint"] = "浅色或深色界面主题",
        ["Settings.Light"] = "浅色",
        ["Settings.Dark"] = "深色",
        ["Settings.AccentColor"] = "强调色",
        ["Settings.AccentColorHint"] = "用于按钮、连接环和选中状态",
        ["Settings.Density"] = "密度",
        ["Settings.DensityHint"] = "间距和控件尺寸",
        ["Settings.Comfortable"] = "宽松",
        ["Settings.Compact"] = "紧凑",
        ["Settings.Language"] = "语言",
        ["Settings.LanguageHint"] = "界面语言。首次启动会使用系统语言。",
        ["Settings.Window"] = "窗口",
        ["Settings.StartMode"] = "启动模式",
        ["Settings.StartModeHint"] = "展开的连接面板或紧凑窗口",
        ["Settings.Expanded"] = "展开",
        ["Settings.Windows"] = "WINDOWS",
        ["Settings.SystemProxy"] = "系统代理",
        ["Settings.SystemProxyHint"] = "连接 SOCKS5 配置时自动把 Windows 代理指向本地 SOCKS5。TUN 不需要此项。",
        ["Settings.SocksListener"] = "SOCKS5 监听器",
        ["Settings.LanAccess"] = "局域网访问",
        ["Settings.LanAccessHint"] = "允许局域网其他设备连接 SOCKS5",
        ["Settings.SocksAddress"] = "SOCKS5 地址",
        ["Settings.SocksAddressHint"] = "所有 SOCKS5 配置共用的本地地址和端口",
        ["Settings.ConnectionTests"] = "连接测试",
        ["Settings.PingHost"] = "Ping 主机",
        ["Settings.PingHostHint"] = "延迟检测地址",
        ["Settings.HttpsUrl"] = "HTTPS 测试 URL",
        ["Settings.HttpsUrlHint"] = "互联网访问检测地址",
        ["Settings.DiagnosticsTimeout"] = "诊断超时",
        ["Settings.DiagnosticsTimeoutHint"] = "最大响应等待时间",
        ["Settings.Version"] = "版本 0.1 · Alpha",
        ["Settings.Description"] = "Proxy Open Hub Windows 客户端 · TrustTunnel 原生核心",
        ["Settings.Updates"] = "更新",
        ["Settings.UpdatesHint"] = "当前版本已是最新",
        ["Settings.Check"] = "检查",
        ["Profile.WindowTitle"] = "配置参数",
        ["Profile.Title"] = "参数：{0}",
        ["Profile.Subtitle"] = "连接、路由、安全和本地代理。",
        ["Profile.Badge"] = "配置",
        ["Profile.Connection"] = "连接",
        ["Profile.Switches"] = "开关",
        ["Profile.RoutingDns"] = "路由 / DNS",
        ["Profile.Local"] = "本地监听器",
        ["Profile.Advanced"] = "高级",
        ["Profile.Name"] = "名称",
        ["Profile.HostnameSni"] = "Hostname / SNI",
        ["Profile.CustomSni"] = "Custom SNI",
        ["Profile.Addresses"] = "地址，每行一个",
        ["Profile.Username"] = "用户名",
        ["Profile.Password"] = "密码",
        ["Profile.Transport"] = "传输",
        ["Profile.ClientMode"] = "客户端模式",
        ["Profile.FallbackProtocol"] = "Fallback 协议",
        ["Profile.TunMode"] = "TUN 系统 VPN",
        ["Profile.SocksMode"] = "SOCKS5 代理",
        ["Profile.PostQuantum"] = "后量子组",
        ["Profile.AntiDpi"] = "Anti-DPI",
        ["Profile.SkipVerification"] = "跳过证书验证",
        ["Profile.KillSwitch"] = "Kill switch",
        ["Profile.ChangeSystemDns"] = "更改系统 DNS",
        ["Profile.UseExistingTun"] = "使用现有 TUN",
        ["Profile.ServiceMode"] = "Windows 服务模式",
        ["Profile.AutoConnect"] = "自动连接",
        ["Profile.RoutingProfile"] = "路由配置",
        ["Profile.RoutingMode"] = "路由模式",
        ["Profile.RoutingGeneral"] = "除规则外全部走 VPN",
        ["Profile.RoutingSelective"] = "只有规则走 VPN",
        ["Profile.DnsUpstreams"] = "DNS upstreams",
        ["Profile.Exclusions"] = "规则：域名、通配符、CIDR",
        ["Profile.IncludedRoutes"] = "包含的 TUN 路由",
        ["Profile.ExcludedRoutes"] = "排除的 TUN 路由",
        ["Profile.KillSwitchPorts"] = "Kill switch 允许端口",
        ["Profile.Mtu"] = "MTU",
        ["Profile.TcpRecv"] = "TCP 接收缓冲区",
        ["Profile.TcpSend"] = "TCP 发送缓冲区",
        ["Profile.LocalHint"] = "这里只保留该配置独有的值。SOCKS5 地址和局域网访问在应用设置中配置。",
        ["Profile.TunBoundIf"] = "TUN bound_if",
        ["Profile.TunDeviceName"] = "TUN 设备名",
        ["Profile.SocksUsername"] = "SOCKS5 用户名",
        ["Profile.SocksPassword"] = "SOCKS5 密码",
        ["Profile.ClientRandom"] = "Client random",
        ["Profile.CertificatePem"] = "证书 PEM",
        ["Profile.SaveTooltip"] = "保存配置参数",
        ["Profile.CancelTooltip"] = "不保存并关闭",
        ["Profile.Valid"] = "配置有效。",
        ["Profile.UnsafeTitle"] = "不安全设置",
        ["Profile.UnsafeMessage"] = "证书验证已禁用，这会降低连接安全性。仍要保存吗？",
        ["Profile.NotSavedTitle"] = "配置未保存",
        ["Routing.Title"] = "路由配置",
        ["Routing.Subtitle"] = "路由配置会应用到主窗口中的服务器。",
        ["Routing.Profiles"] = "配置",
        ["Routing.Name"] = "名称",
        ["Routing.Description"] = "描述",
        ["Routing.Mode"] = "路由模式",
        ["Routing.General"] = "除规则外全部走 VPN",
        ["Routing.Selective"] = "只有规则走 VPN",
        ["Routing.Presets"] = "快速预设",
        ["Routing.RuBypass"] = "RU 不走 VPN",
        ["Routing.RuBypassTip"] = "添加 .ru、.su 和 .рф 规则",
        ["Routing.LocalBypass"] = "局域网不走 VPN",
        ["Routing.LocalBypassShort"] = "局域网不走",
        ["Routing.LocalBypassTip"] = "添加私有 IPv4 网络到 VPN 外",
        ["Routing.SelectivePreset"] = "只有列表走 VPN",
        ["Routing.SelectivePresetTip"] = "切换为 selective 模式",
        ["Routing.NewProfile"] = "路由配置",
        ["Routing.Rules"] = "规则：域名、通配符、CIDR",
        ["Routing.RulesHint"] = "每行一条规则：*.ru, *.xn--p1ai, example.com, 10.0.0.0/8",
        ["Routing.KillSwitchPorts"] = "Kill switch 允许端口",
        ["Routing.SaveProfile"] = "保存配置",
        ["Routing.SaveProfileTip"] = "保存所选路由配置",
        ["Toml.Title"] = "编辑 TOML",
        ["Toml.Subtitle"] = "编辑 TOML。预览中会隐藏密钥，但保存和复制时使用完整 TOML。",
        ["Toml.ShowSensitive"] = "显示敏感数据",
        ["Toml.ShowSensitiveTip"] = "在编辑器中显示 password、client_random 和 certificate",
        ["Toml.Copy"] = "复制 TOML",
        ["Import.Title"] = "导入配置",
        ["Import.Subtitle"] = "如果剪贴板中有 tt:// 链接或 TOML，可以直接添加配置。",
        ["Import.CheckingClipboard"] = "正在检查剪贴板...",
        ["Import.ClipboardFound"] = "剪贴板中找到 TrustTunnel 链接。",
        ["Import.ClipboardMissing"] = "剪贴板中没有 TrustTunnel 链接。可手动粘贴链接或导入 TOML。",
        ["Import.ClipboardNoText"] = "剪贴板中没有文本。",
        ["Import.Failed"] = "导入失败",
        ["Import.FromClipboard"] = "从剪贴板导入",
        ["Import.PasteLink"] = "粘贴链接",
        ["Import.Toml"] = "TOML",
        ["Import.Manual"] = "手动",
        ["ImportToml.Title"] = "导入 TOML",
        ["ImportToml.Subtitle"] = "粘贴 TOML 配置。密码会转移到 secret store。",
        ["ImportToml.Import"] = "导入",

        ["Main.Servers"] = "服务器",
        ["Main.AddServer"] = "添加服务器",
        ["Main.NoServer"] = "未选择服务器",
        ["Main.ImportConfig"] = "导入配置",
        ["Main.ImportOrAdd"] = "导入配置或添加配置文件。",
        ["Main.Connect"] = "连接",
        ["Main.Disconnect"] = "断开",
        ["Main.Connecting"] = "正在连接...",
        ["Main.Disconnecting"] = "正在断开...",
        ["Main.Reconnecting"] = "正在重连...",
        ["Main.Connected"] = "已连接",
        ["Main.Disconnected"] = "未连接",
        ["Main.ConnectionError"] = "连接错误",
        ["Main.Ready"] = "准备连接",
        ["Main.SelectServerAndConnect"] = "选择服务器并连接",
        ["Main.Download"] = "下载",
        ["Main.Upload"] = "上传",
        ["Main.Protocol"] = "协议",
        ["Main.Ping"] = "PING",
        ["Main.Session"] = "会话",
        ["Main.Route"] = "路由",
        ["Main.OpenCores"] = "已打开核心 · 1",
        ["Main.ActiveCore"] = "活动核心",
        ["Main.Open"] = "打开",
        ["Main.Soon"] = "即将推出",
        ["Main.TrustedRelease"] = "可信 GitHub release",
        ["Main.ToggleTheme"] = "切换浅色/深色主题",
        ["Main.RoutingProfiles"] = "路由配置",
        ["Main.EditToml"] = "编辑 TOML",
        ["Main.Logs"] = "日志",
        ["Main.Settings"] = "应用设置",
        ["Main.ServerParameters"] = "服务器参数",
        ["Main.DeleteServerTitle"] = "删除服务器",
        ["Main.DeleteServerMessage"] = "删除“{0}”及相关密钥？",
        ["Main.SessionActive"] = "活动",
        ["Main.SessionStart"] = "启动",
        ["Main.SessionRetry"] = "重试",
        ["Main.SessionStop"] = "停止",
        ["Main.SessionError"] = "错误",
        ["Main.SelectServerTitle"] = "Proxy Open Hub",
        ["Main.SelectServerMessage"] = "请先选择服务器。",

        ["Manual.Title"] = "添加服务器",
        ["Manual.Subtitle"] = "只填写基本字段。其余内容可稍后在配置参数中修改。",
        ["Manual.Address"] = "Host:port 地址",
        ["Manual.QuickOptions"] = "快速选项",
        ["Manual.SaveTooltip"] = "保存服务器",
        ["TextViewer.CopyHint"] = "内容可以复制到剪贴板。",
        ["TextViewer.ViewHint"] = "文本内容预览。",
        ["TextViewer.Copy"] = "复制",
    };

    private static readonly IReadOnlyDictionary<string, string> Persian = new Dictionary<string, string>
    {
        ["Common.Save"] = "ذخیره",
        ["Common.Cancel"] = "لغو",
        ["Common.Close"] = "بستن",
        ["Common.Apply"] = "اعمال",
        ["Common.Reset"] = "بازنشانی",
        ["Common.Delete"] = "حذف",
        ["Common.Duplicate"] = "کپی",
        ["Common.CreateProfile"] = "ساخت پروفایل",
        ["Common.DeleteProfile"] = "حذف پروفایل انتخاب‌شده",
        ["Common.ShowPassword"] = "نمایش گذرواژه",
        ["Common.ShowSocksPassword"] = "نمایش گذرواژه SOCKS5",
        ["Common.ShowClientRandom"] = "نمایش client random",
        ["Common.None"] = "هیچ‌کدام",
        ["Language.English"] = "English",
        ["Language.Russian"] = "Русский",
        ["Language.Chinese"] = "中文",
        ["Language.Persian"] = "فارسی",
        ["Settings.Title"] = "تنظیمات",
        ["Settings.Appearance"] = "ظاهر",
        ["Settings.Proxy"] = "پروکسی",
        ["Settings.Diagnostics"] = "عیب‌یابی",
        ["Settings.About"] = "درباره",
        ["Settings.Theme"] = "پوسته",
        ["Settings.ColorScheme"] = "طرح رنگ",
        ["Settings.ColorSchemeHint"] = "پوسته روشن یا تیره رابط کاربری",
        ["Settings.Light"] = "روشن",
        ["Settings.Dark"] = "تیره",
        ["Settings.AccentColor"] = "رنگ تأکیدی",
        ["Settings.AccentColorHint"] = "برای دکمه‌ها، حلقه و انتخاب استفاده می‌شود",
        ["Settings.Density"] = "تراکم",
        ["Settings.DensityHint"] = "فاصله‌ها و اندازه کنترل‌ها",
        ["Settings.Comfortable"] = "باز",
        ["Settings.Compact"] = "فشرده",
        ["Settings.Language"] = "زبان",
        ["Settings.LanguageHint"] = "زبان رابط. در اجرای اول از زبان سیستم استفاده می‌شود.",
        ["Settings.Window"] = "پنجره",
        ["Settings.StartMode"] = "حالت شروع",
        ["Settings.StartModeHint"] = "پنجره باز با پنل اتصال یا حالت فشرده",
        ["Settings.Expanded"] = "باز",
        ["Settings.Windows"] = "WINDOWS",
        ["Settings.SystemProxy"] = "پروکسی سیستم",
        ["Settings.SystemProxyHint"] = "هنگام اتصال پروفایل SOCKS5، پروکسی Windows را روی SOCKS5 محلی تنظیم می‌کند. برای TUN لازم نیست.",
        ["Settings.SocksListener"] = "شنونده SOCKS5",
        ["Settings.LanAccess"] = "دسترسی LAN",
        ["Settings.LanAccessHint"] = "اجازه اتصال به SOCKS5 از دستگاه‌های دیگر شبکه محلی",
        ["Settings.SocksAddress"] = "آدرس SOCKS5",
        ["Settings.SocksAddressHint"] = "آدرس و پورت محلی مشترک برای همه پروفایل‌های SOCKS5",
        ["Settings.ConnectionTests"] = "تست‌های اتصال",
        ["Settings.PingHost"] = "میزبان Ping",
        ["Settings.PingHostHint"] = "آدرس برای بررسی تأخیر",
        ["Settings.HttpsUrl"] = "URL تست HTTPS",
        ["Settings.HttpsUrlHint"] = "آدرس برای بررسی دسترسی اینترنت",
        ["Settings.DiagnosticsTimeout"] = "مهلت عیب‌یابی",
        ["Settings.DiagnosticsTimeoutHint"] = "حداکثر زمان انتظار پاسخ",
        ["Settings.Version"] = "نسخه 0.1 · Alpha",
        ["Settings.Description"] = "کلاینت Windows برای Proxy Open Hub · هسته بومی TrustTunnel",
        ["Settings.Updates"] = "به‌روزرسانی‌ها",
        ["Settings.UpdatesHint"] = "نسخه فعلی به‌روز است",
        ["Settings.Check"] = "بررسی",
        ["Profile.WindowTitle"] = "پارامترهای پروفایل",
        ["Profile.Title"] = "پارامترها: {0}",
        ["Profile.Subtitle"] = "اتصال، مسیرها، امنیت و پروکسی‌های محلی.",
        ["Profile.Badge"] = "پروفایل",
        ["Profile.Connection"] = "اتصال",
        ["Profile.Switches"] = "گزینه‌ها",
        ["Profile.RoutingDns"] = "مسیرها / DNS",
        ["Profile.Local"] = "شنونده محلی",
        ["Profile.Advanced"] = "پیشرفته",
        ["Profile.Name"] = "نام",
        ["Profile.HostnameSni"] = "Hostname / SNI",
        ["Profile.CustomSni"] = "Custom SNI",
        ["Profile.Addresses"] = "آدرس‌ها، هر خط یکی",
        ["Profile.Username"] = "نام کاربری",
        ["Profile.Password"] = "گذرواژه",
        ["Profile.Transport"] = "انتقال",
        ["Profile.ClientMode"] = "حالت کلاینت",
        ["Profile.FallbackProtocol"] = "پروتکل fallback",
        ["Profile.TunMode"] = "TUN system VPN",
        ["Profile.SocksMode"] = "SOCKS5 proxy",
        ["Profile.PostQuantum"] = "گروه پساکوانتومی",
        ["Profile.AntiDpi"] = "Anti-DPI",
        ["Profile.SkipVerification"] = "رد کردن بررسی گواهی",
        ["Profile.KillSwitch"] = "Kill switch",
        ["Profile.ChangeSystemDns"] = "تغییر DNS سیستم",
        ["Profile.UseExistingTun"] = "استفاده از TUN موجود",
        ["Profile.ServiceMode"] = "حالت سرویس Windows",
        ["Profile.AutoConnect"] = "اتصال خودکار",
        ["Profile.RoutingProfile"] = "پروفایل مسیر",
        ["Profile.RoutingMode"] = "حالت مسیریابی",
        ["Profile.RoutingGeneral"] = "VPN برای همه چیز به جز قوانین",
        ["Profile.RoutingSelective"] = "VPN فقط برای قوانین",
        ["Profile.DnsUpstreams"] = "DNS upstreams",
        ["Profile.Exclusions"] = "قوانین: دامنه، wildcard و CIDR",
        ["Profile.IncludedRoutes"] = "مسیرهای TUN شامل‌شده",
        ["Profile.ExcludedRoutes"] = "مسیرهای TUN مستثنا",
        ["Profile.KillSwitchPorts"] = "پورت‌های مجاز kill switch",
        ["Profile.Mtu"] = "MTU",
        ["Profile.TcpRecv"] = "بافر دریافت TCP",
        ["Profile.TcpSend"] = "بافر ارسال TCP",
        ["Profile.LocalHint"] = "اینجا فقط مقادیر مخصوص همین پروفایل می‌مانند. آدرس SOCKS5 و دسترسی LAN در تنظیمات برنامه تنظیم می‌شوند.",
        ["Profile.TunBoundIf"] = "TUN bound_if",
        ["Profile.TunDeviceName"] = "نام دستگاه TUN",
        ["Profile.SocksUsername"] = "نام کاربری SOCKS5",
        ["Profile.SocksPassword"] = "گذرواژه SOCKS5",
        ["Profile.ClientRandom"] = "Client random",
        ["Profile.CertificatePem"] = "گواهی PEM",
        ["Profile.SaveTooltip"] = "ذخیره پارامترهای پروفایل",
        ["Profile.CancelTooltip"] = "بستن بدون ذخیره",
        ["Profile.Valid"] = "پروفایل معتبر است.",
        ["Profile.UnsafeTitle"] = "تنظیم ناامن",
        ["Profile.UnsafeMessage"] = "بررسی گواهی غیرفعال است. این امنیت اتصال را کاهش می‌دهد. ذخیره شود؟",
        ["Profile.NotSavedTitle"] = "پروفایل ذخیره نشد",
        ["Routing.Title"] = "پروفایل‌های مسیریابی",
        ["Routing.Subtitle"] = "پروفایل‌های مسیریابی روی سرورهای پنجره اصلی اعمال می‌شوند.",
        ["Routing.Profiles"] = "پروفایل‌ها",
        ["Routing.Name"] = "نام",
        ["Routing.Description"] = "توضیح",
        ["Routing.Mode"] = "حالت مسیریابی",
        ["Routing.General"] = "VPN برای همه چیز به جز قوانین",
        ["Routing.Selective"] = "VPN فقط برای قوانین",
        ["Routing.Presets"] = "پیش‌تنظیم‌های سریع",
        ["Routing.RuBypass"] = "RU خارج از VPN",
        ["Routing.RuBypassTip"] = "افزودن قوانین برای .ru، .su و .рф",
        ["Routing.LocalBypass"] = "شبکه محلی خارج از VPN",
        ["Routing.LocalBypassShort"] = "شبکه محلی خارج",
        ["Routing.LocalBypassTip"] = "افزودن شبکه‌های خصوصی IPv4 خارج از VPN",
        ["Routing.SelectivePreset"] = "فقط فهرست از VPN",
        ["Routing.SelectivePresetTip"] = "تغییر پروفایل به حالت selective",
        ["Routing.NewProfile"] = "نمایه مسیریابی",
        ["Routing.Rules"] = "قوانین: دامنه، wildcard و CIDR",
        ["Routing.RulesHint"] = "هر خط یک قانون: *.ru, *.xn--p1ai, example.com, 10.0.0.0/8",
        ["Routing.KillSwitchPorts"] = "پورت‌های مجاز kill switch",
        ["Routing.SaveProfile"] = "ذخیره پروفایل",
        ["Routing.SaveProfileTip"] = "ذخیره پروفایل مسیریابی انتخاب‌شده",
        ["Toml.Title"] = "ویرایش TOML",
        ["Toml.Subtitle"] = "TOML را ویرایش کنید. رازها در پیش‌نمایش مخفی هستند، اما کامل ذخیره و کپی می‌شوند.",
        ["Toml.ShowSensitive"] = "نمایش داده‌های حساس",
        ["Toml.ShowSensitiveTip"] = "نمایش password، client_random و certificate در ویرایشگر",
        ["Toml.Copy"] = "کپی TOML",
        ["Import.Title"] = "وارد کردن پروفایل",
        ["Import.Subtitle"] = "اگر clipboard شامل لینک tt:// یا TOML باشد، پروفایل فوراً اضافه می‌شود.",
        ["Import.CheckingClipboard"] = "در حال بررسی clipboard...",
        ["Import.ClipboardFound"] = "لینک TrustTunnel در clipboard پیدا شد.",
        ["Import.ClipboardMissing"] = "لینک TrustTunnel در clipboard پیدا نشد. می‌توانید لینک را دستی وارد کنید یا TOML را ایمپورت کنید.",
        ["Import.ClipboardNoText"] = "clipboard متن ندارد.",
        ["Import.Failed"] = "ایمپورت انجام نشد",
        ["Import.FromClipboard"] = "وارد کردن از clipboard",
        ["Import.PasteLink"] = "چسباندن لینک",
        ["Import.Toml"] = "TOML",
        ["Import.Manual"] = "دستی",
        ["ImportToml.Title"] = "وارد کردن TOML",
        ["ImportToml.Subtitle"] = "کانفیگ TOML را بچسبانید. گذرواژه‌ها به secret store منتقل می‌شوند.",
        ["ImportToml.Import"] = "وارد کردن",

        ["Main.Servers"] = "سرورها",
        ["Main.AddServer"] = "افزودن سرور",
        ["Main.NoServer"] = "سروری انتخاب نشده",
        ["Main.ImportConfig"] = "وارد کردن کانفیگ",
        ["Main.ImportOrAdd"] = "یک کانفیگ وارد کنید یا پروفایل اضافه کنید.",
        ["Main.Connect"] = "اتصال",
        ["Main.Disconnect"] = "قطع اتصال",
        ["Main.Connecting"] = "در حال اتصال...",
        ["Main.Disconnecting"] = "در حال قطع اتصال...",
        ["Main.Reconnecting"] = "در حال اتصال دوباره...",
        ["Main.Connected"] = "متصل",
        ["Main.Disconnected"] = "قطع شده",
        ["Main.ConnectionError"] = "خطای اتصال",
        ["Main.Ready"] = "آماده اتصال",
        ["Main.SelectServerAndConnect"] = "سرور را انتخاب و متصل شوید",
        ["Main.Download"] = "دریافت",
        ["Main.Upload"] = "ارسال",
        ["Main.Protocol"] = "پروتکل",
        ["Main.Ping"] = "PING",
        ["Main.Session"] = "نشست",
        ["Main.Route"] = "مسیر",
        ["Main.OpenCores"] = "هسته‌های باز · 1",
        ["Main.ActiveCore"] = "هسته فعال",
        ["Main.Open"] = "باز",
        ["Main.Soon"] = "به‌زودی",
        ["Main.TrustedRelease"] = "انتشار قابل اعتماد GitHub",
        ["Main.ToggleTheme"] = "تغییر پوسته روشن/تیره",
        ["Main.RoutingProfiles"] = "پروفایل‌های مسیر",
        ["Main.EditToml"] = "ویرایش TOML",
        ["Main.Logs"] = "لاگ‌ها",
        ["Main.Settings"] = "تنظیمات برنامه",
        ["Main.ServerParameters"] = "پارامترهای سرور",
        ["Main.DeleteServerTitle"] = "حذف سرور",
        ["Main.DeleteServerMessage"] = "«{0}» و رمزهای مرتبط حذف شوند؟",
        ["Main.SessionActive"] = "فعال",
        ["Main.SessionStart"] = "شروع",
        ["Main.SessionRetry"] = "تلاش دوباره",
        ["Main.SessionStop"] = "توقف",
        ["Main.SessionError"] = "خطا",
        ["Main.SelectServerTitle"] = "Proxy Open Hub",
        ["Main.SelectServerMessage"] = "ابتدا یک سرور انتخاب کنید.",

        ["Manual.Title"] = "افزودن سرور",
        ["Manual.Subtitle"] = "فقط فیلدهای پایه را پر کنید. باقی موارد بعداً در تنظیمات پروفایل قابل تغییر است.",
        ["Manual.Address"] = "آدرس host:port",
        ["Manual.QuickOptions"] = "گزینه‌های سریع",
        ["Manual.SaveTooltip"] = "ذخیره سرور",
        ["TextViewer.CopyHint"] = "محتوا را می‌توان در clipboard کپی کرد.",
        ["TextViewer.ViewHint"] = "پیش‌نمایش محتوای متنی.",
        ["TextViewer.Copy"] = "کپی",
    };

    private static readonly LocalizationManager Current = new();

    private IReadOnlyDictionary<string, string> _strings = English;

    public static LocalizationManager Instance => Current;

    public event PropertyChangedEventHandler? PropertyChanged;

    public AppLanguage CurrentLanguage { get; private set; } = AppLanguage.English;

    public ReadOnlyCollection<LanguageOption> Languages { get; } = Array.AsReadOnly(new[]
    {
        new LanguageOption(AppLanguage.English, "English"),
        new LanguageOption(AppLanguage.Russian, "Русский"),
        new LanguageOption(AppLanguage.Chinese, "中文"),
        new LanguageOption(AppLanguage.Persian, "فارسی")
    });

    public string this[string key] => Translate(key);

    public static AppLanguage Resolve(AppLanguage language)
    {
        if (language != AppLanguage.System)
        {
            return language;
        }

        var culture = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        return culture switch
        {
            "ru" => AppLanguage.Russian,
            "zh" => AppLanguage.Chinese,
            "fa" => AppLanguage.Persian,
            _ => AppLanguage.English
        };
    }

    public void Apply(AppLanguage language)
    {
        var resolved = Resolve(language);
        if (resolved == CurrentLanguage)
        {
            return;
        }

        CurrentLanguage = resolved;
        _strings = resolved switch
        {
            AppLanguage.Russian => Russian,
            AppLanguage.Chinese => Chinese,
            AppLanguage.Persian => Persian,
            _ => English
        };
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
    }

    public string Translate(string key)
    {
        return _strings.TryGetValue(key, out var value)
            ? value
            : English.TryGetValue(key, out var fallback)
                ? fallback
                : key;
    }

    public string Format(string key, params object[] args)
    {
        return string.Format(CultureInfo.CurrentCulture, Translate(key), args);
    }
}

public sealed record LanguageOption(AppLanguage Language, string Name)
{
    public override string ToString() => Name;
}
