[package]
name = "poh_cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
poh_core = { path = "../poh_core" }
poh_core_runner = { path = "../poh_core_runner" }
poh_core_session = { path = "../poh_core_session" }
poh_core_store = { path = "../poh_core_store" }
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Networking_WinInet",
    "Win32_Security_Cryptography",
    "Win32_System_Threading",
    "Win32_System_Console",
] }
